### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by JurajKabzan** [richards-tech/MPU9150Lib#5]
Hello, I checked your library. First of all I was really surprise how well everything works until.

I use teensy 3.1 on 96 Mhz what is quite fast. I reallysed that your update rade in function MPU.red() is juer every 30ms what si wayyy slow. Do you have any ide why? 

I checked your basic Arduino9150 sketch, I compare it with jeffs i2cdevlib and his dmp code just v4.1 and there update rate is 0.001ms so is really good. Do you have any idea?

Thank you

**Comment by richardbarnett** [comment]
This library is no longer supported and has never been tested on a Teensy! Why not use RTIMULib-Teensy?
