### ISSUE TITLE
MPU9150 initialization problems (that go away when power cycled)

### ISSUE THREAD

**Issue by altineller** [richards-tech/MPU9150Lib#6]
So everything works ok, but If I reset the board couple of times, it will cease to init DMP. Printing out:

Energia9150 starting using device 0
mpu_init failed with code: -1
0

Well if I power cycle the mpu unit (I even made a transistor driven circuit for it, shutting off the power for 10ms, then turning it on, upon reset) - the unit will load dmp code everytime.

From another library dealing with the same sensor:

https://code.google.com/p/nav6/source/browse/trunk/arduino/nav6/nav6.ino

we see some code that is at the beginning to reset the i2c bus. (I tested this code, but however if this i2c reset routine runs, than it will NOT load DMP code everytime) 

The author claims, if the devices on the i2c bus were not reset, this code will fix it, but unfortunately it will not work.

Did you come across this problem? 

Best regards,

**Comment by richardbarnett** [comment]
I have seen it - not with an Arduino but with SAM3X, Teensy 3.1 etc. It seems that the MPU-9150 itself hangs up and I don't know of any way to reset it other than a power cycle.

**Comment by altineller** [comment]
Hello,

Yes the board I am running this on is an TM4C123 from texas instruments running with energia.

I am suspecting it is a problem with the i2c code, circuitry on the host platform.

Best Regards,
